# Generated by Django 5.2.4 on 2025-08-13 13:02

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_studentprofile_internship_location_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentprofile',
            name='supervisor',
            field=models.ForeignKey(blank=True, limit_choices_to={'role': 'supervisor'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='supervised_students', to=settings.AUTH_USER_MODEL),
        ),
    ]
