# Generated by Django 5.2.4 on 2025-08-20 09:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0001_initial'),
        ('users', '0003_alter_studentprofile_supervisor'),
    ]

    operations = [
        migrations.AlterField(
            model_name='supervisorprofile',
            name='department',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='school.department'),
        ),
    ]
